### ISSUE TITLE
Extension not working on Fedora 16

### ISSUE THREAD

**Issue by dequegorg** [brianrobles204/Music-Integration#20]
I installed the extension from gnome's site, the icon does not appear in the panel.

**Comment by jrub** [comment]
It works for me. Open Rhytmbox, play some music, and click on the sound icon. Don't you see the extra info and controls for the playing music?

**Comment by dequegorg** [comment]
Nope. The icon does not appear in the panel. There is one in the tray however.
I am using Fedora 16.

**Comment by jrub** [comment]
I mean, you had the sound icon before installing the extension? And after installing, you have back/forward buttons when playing music if you click the sound icon? That's the default, then you can change it to a diferent specific  "musical-note" button as per README.

Sorry about my insistence, but I'm using Fedora 16 and it's working flawlessly for me.

**Comment by dequegorg** [comment]
I have a sound icon on the panel with which I can change the volume and access sound settings.
When playing music with either Rhythmbox or Banshee, this sound icon is not affected.
I tried Gnome-Shell with this extension on Ubuntu (unless I am mistaken and there is another extension similar to yours) and it added another icon on the panel with a music note icon.
This icon I can see in the tray when playing music with Rhythmbox (it says Rhythmbox Integration), but not with Banshee.
See [screenshot](https://lh5.googleusercontent.com/-tg7g2irQp2A/Tzo4ddHVXBI/AAAAAAAACoU/mOvxRzqM8a0/s800/Screenshot%2520at%25202012-02-14%252011%253A28%253A46.png)

**Comment by jrub** [comment]
Well, the extension can work either on the sound menu or on a new music note menu. The [README](https://github.com/brianrobles204/Music-Integration/blob/master/README.md) is pretty self-explanatory with screenshots. It also explains that if you install the extension via Gnome Extensions website, it gets on the sound icon (without preferences for changing it), and how to change it. It also specifies Banshee is supported when the DBus Mpris plugin is enabled.

Did you install via [Gnome extension page](https://extensions.gnome.org/extension/30/music-integration/)?

Are you using Ubuntu with Unity or classic-gnome? I think you can't use extensions with Unity, but I've not tested it (I use Fedora).

**Comment by dequegorg** [comment]
I have installed the extension via the Gnome extension page indeed.
Now I am on Fedora 16, earlier I tried it on Ubuntu + Gnome Shell, on which the extension worked flawlessly.
I will try to re-install the extension from Github instead. I keep you posted.

**Comment by dequegorg** [comment]
OK I reinstalled and it's working now. I indeed had to enable the Mpris plugin to get Banshee in to show too.
