### ISSUE TITLE
Unable to run Extension

### ISSUE THREAD

**Issue by LumiWasTaken** [brianrobles204/Music-Integration#29]
`JS ERROR: Extension music-integration@brianrobles204: ImportError: No JS module 'dbus' found in search path
                                         @/usr/share/gnome-shell/extensions/music-integration@brianrobles204/extension.js:4:14
`
gnome-shell --version
GNOME Shell 3.38.1

**Comment by hucuyuu** [comment]
same problem as you

**Comment by pavkamlc** [comment]
On fedora 33 (gnome shell 3.38.0) the some problem

**Comment by pavkamlc** [comment]
Maybe is imports.dbus obsoleted. In gnome example is used Gio.DBusProxy
https://wiki.gnome.org/Gjs/Examples/DBusClient

**Comment by pavkamlc** [comment]
In gnome 3.38 is needed change tweener too:

//const Tweener = imports.ui.tweener;
const Tweener = imports.tweener.tweener;

**Comment by TrapTheOnly** [comment]
Any news how to solve this?
