### ISSUE TITLE
music-int-pref.py doesn't work with python 3

### ISSUE THREAD

**Issue by oxayotl** [brianrobles204/Music-Integration#3]
because it uses a mix of spaces and tabulation.
To fix it, I opened music-int-pref.py with gedit, activated plugin “show blankspace” plugin (actual name might be a little different, I'm not using English locale), then selected a tabulation, and use “Search and replace” to replace all tabulations by 8 spaces.
You can also, by the way, add python-gobject to the list of dependancies.

**Comment by brianrobles204** [comment]
Updated the docs and fixed the python script. Thanks!
