### ISSUE TITLE
Small UI improvement for the configuration window

### ISSUE THREAD

**Issue by oxayotl** [brianrobles204/Music-Integration#4]
I made a very small patch (2 lines) that attribute an icon to the configuration window, and removes a useless and confusing entry in the combobox.
I don't know how to add a patch on github, so I'm pasting it here :
--- music-int-pref.py.old   2011-12-05 15:54:51.592340855 +0100
+++ music-int-pref.py   2011-12-05 15:54:36.535431011 +0100
@@ -11,6 +11,7 @@
         window = Gtk.Window()
         window.connect('destroy', lambda w: Gtk.main_quit())
         window.set_title('Music Integration Preferences')
-        window.set_icon_name(Gtk.STOCK_PREFERENCES)
       window.set_default_size(400, 160)  
       window.set_border_width(6)

@@ -46,7 +47,6 @@
         player = Gtk.ComboBoxText()

```
     hplayerbox.pack_start(player, False, True, 0)
```
-        player.append_text('Choose a setup :')
       player.append_text('Player as Indicator in Panel')
       player.append_text('Player in Volume Menu')
       player.append_text('Notifications only')

**Comment by brianrobles204** [comment]
actually, I believe you need to fork this extension and use git to update your own branch, but anyway...

I'm not sure how to read your second patch. There's a formatting error. Maybe you should just use pastebin.com for showing your changes instead :)

**Comment by brianrobles204** [comment]
Ok, I understand your patch, but I can't implement the second one because the preferences will then jump by one. (eg selecting the second choice, "Volume Menu", will make the extension use the first choice, "Indicator in Panel"). I will flag this as a known issue and change the extension.js to read it correctly.

**Comment by brianrobles204** [comment]
The preference window has been updated, thanks.
