### ISSUE TITLE
Player buttons not displaying fully

### ISSUE THREAD

**Issue by ludenticus** [brianrobles204/Music-Integration#5]
The buttons of the pop up menu, on the panel as well as on the tray are not displaying at their full size. This bug started after I followed your instructions to turn on the preferences.

http://ubuntuone.com/0x3ulPIDAlwtNNb0uR2cZE

**Comment by brianrobles204** [comment]
What GS theme are you using? What icon theme?(this one is important) Have you been using any other extensions? Sometimes the stylesheets could conflict, although that seems unlikely in this case. Perhaps you should try rebooting, apparently the problem just went away for another guy.

**Comment by ludenticus** [comment]
You're right. The problem was the icon theme: Elementary. Under any other (Faenza, Gnome, Mac-Lion, etc.) it doesn't happen.

**Comment by brianrobles204** [comment]
I thought so. Apparently some other extensions are having problems with the elementary icon theme too. Hopefully those guys fix it upstream. Thanks for the info and for trying out my extension.
